//! Differential test against the **real** vanilla 26.1.2 server (P03-T07, L6).
//!
//! Ignored by default because it needs a vanilla server jar and a vanilla world
//! on disk. Run it with:
//!
//! ```text
//! MC_VANILLA_JAR=<...>/server.jar \
//! MC_VANILLA_WORLD=<...>/vanilla-world-26.1.2/world \
//! MC_JAVA=<path to java>                       # optional, defaults to `java` \
//! cargo test -p mc-persistence --test vanilla_differential -- --ignored --nocapture
//! ```
//!
//! What it proves, and why it is the strongest evidence this phase can produce:
//!
//! 1. every chunk of a world generated by vanilla is decoded by our reader;
//! 2. every one of those chunks is re-encoded by our writer into a fresh region
//!    file, and re-read back identically (semantic equality of the whole chunk);
//! 3. **vanilla 26.1.2 starts on the rewritten world**, loads chunks, saves
//!    them again and exits with no chunk/level error in its log.
//!
//! Step 3 is what turns "our bytes are self-consistent" into "vanilla accepts
//! our bytes". Without it, a compatibility claim would rest on our own reader
//! agreeing with our own writer (AGENTS.md section 3.1).

// Binary-format tests narrow and widen integers (sector counts, bit widths,
// chunk coordinates) and keep long end-to-end scenario functions readable; the
// same exemption is documented in the crate roots.
#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_lossless,
    clippy::too_many_lines
)]

use mc_persistence::chunk::{ChunkData, ChunkPos};
use mc_persistence::dimension::Dimension;
use mc_persistence::level::LevelDat;
use mc_persistence::world::WorldStorage;
use std::path::{Path, PathBuf};
use std::process::Command;

fn env_path(key: &str) -> Option<PathBuf> {
    std::env::var_os(key).map(PathBuf::from)
}

/// Recursively copy a directory, skipping the session lock.
fn copy_tree(from: &Path, to: &Path) -> std::io::Result<()> {
    std::fs::create_dir_all(to)?;
    for entry in std::fs::read_dir(from)? {
        let entry = entry?;
        let name = entry.file_name();
        if name == "session.lock" {
            continue;
        }
        let target = to.join(&name);
        if entry.file_type()?.is_dir() {
            copy_tree(&entry.path(), &target)?;
        } else {
            std::fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

/// Every region file of every dimension in the world.
fn region_files(root: &Path) -> Vec<(Dimension, PathBuf)> {
    let mut out = Vec::new();
    let dimensions = root.join("dimensions");
    if let Ok(namespaces) = std::fs::read_dir(&dimensions) {
        for namespace in namespaces.flatten() {
            if let Ok(values) = std::fs::read_dir(namespace.path()) {
                for value in values.flatten() {
                    let region_dir = value.path().join("region");
                    let Ok(files) = std::fs::read_dir(&region_dir) else {
                        continue;
                    };
                    let key = format!(
                        "{}:{}",
                        namespace.file_name().to_string_lossy(),
                        value.file_name().to_string_lossy()
                    );
                    let Ok(dimension) = Dimension::parse(&key) else {
                        continue;
                    };
                    for file in files.flatten() {
                        let path = file.path();
                        if path.extension().is_some_and(|ext| ext == "mca") {
                            out.push((dimension.clone(), path));
                        }
                    }
                }
            }
        }
    }
    out.sort();
    out
}

/// Parse `r.<x>.<z>.mca` into region coordinates.
fn region_coords(path: &Path) -> Option<(i32, i32)> {
    let stem = path.file_stem()?.to_string_lossy().into_owned();
    let rest = stem.strip_prefix("r.")?;
    let (x, z) = rest.split_once('.')?;
    Some((x.parse().ok()?, z.parse().ok()?))
}

#[test]
#[ignore = "requires MC_VANILLA_JAR and MC_VANILLA_WORLD"]
fn a_rewritten_vanilla_world_is_accepted_by_vanilla_26_1_2() {
    let jar = env_path("MC_VANILLA_JAR").expect("MC_VANILLA_JAR must point at a 26.1.2 server.jar");
    let source = env_path("MC_VANILLA_WORLD").expect("MC_VANILLA_WORLD must point at a world dir");
    let java = std::env::var("MC_JAVA").unwrap_or_else(|_| "java".to_owned());

    // A scratch server directory; the world keeps its vanilla folder name so
    // server.properties can point at it unchanged.
    let scratch = std::env::temp_dir().join(format!("mc-vanilla-diff-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&scratch);
    let world_name = source
        .file_name()
        .expect("world dir has a name")
        .to_string_lossy()
        .into_owned();
    let rewritten_world = scratch.join(&world_name);
    copy_tree(&source, &rewritten_world).expect("copy the vanilla world");
    println!("rewritten world: {}", rewritten_world.display());

    // --- 1+2: read every vanilla chunk, rewrite it through our writer --------
    let mut storage = WorldStorage::open(&rewritten_world, 0).expect("open the copied world");
    let regions = region_files(&rewritten_world);
    assert!(
        !regions.is_empty(),
        "no region files found under {source:?}"
    );
    let level_before = storage.level().cloned().expect("level.dat");
    assert_eq!(level_before.data_version, 4790);
    println!("level.dat: DataVersion={}", level_before.data_version);

    let mut chunks_rewritten = 0usize;
    for (dimension, region_path) in &regions {
        let Some((region_x, region_z)) = region_coords(region_path) else {
            continue;
        };
        let mut decoded_here = 0usize;
        for local_x in 0..32 {
            for local_z in 0..32 {
                let pos = ChunkPos::new(region_x * 32 + local_x, region_z * 32 + local_z);
                let chunk = match storage.read_chunk(dimension, pos) {
                    Ok(Some(chunk)) => chunk,
                    Ok(None) => continue,
                    Err(e) => panic!("cannot read {pos:?} of {dimension}: {e}"),
                };
                // The re-encoded chunk must decode back to exactly the same
                // semantic content before it is written anywhere.
                let round_tripped =
                    ChunkData::from_nbt_bytes(&chunk.to_nbt_bytes().expect("encodes"))
                        .expect("re-decodes");
                assert_eq!(round_tripped, chunk, "{pos:?} lost data on re-encode");
                storage
                    .queue_chunk_save(dimension, &chunk)
                    .expect("queues the chunk");
                decoded_here += 1;
            }
        }
        println!(
            "{}: {decoded_here} chunks decoded from {}",
            dimension,
            region_path.display()
        );
        chunks_rewritten += decoded_here;
    }
    assert!(chunks_rewritten > 0, "no chunks were decoded at all");
    let report = storage.flush().expect("flush");
    assert!(report.is_clean(), "{report:?}");
    assert_eq!(report.chunks_written, chunks_rewritten);
    storage.close().expect("close");
    println!("rewrote {chunks_rewritten} chunks through our writer");

    // A marker only our bytes can carry: stamp a distinctive block into a chunk
    // vanilla is certain to load (the spawn chunk). If vanilla regenerated the
    // terrain instead of reading our chunk, the marker disappears — which is
    // what makes "vanilla started" mean "vanilla read our data".
    let marker = mc_persistence::chunk::BlockState::new("minecraft:diamond_block");
    let marker_pos = ChunkPos::new(-37, -24);
    let marker_section_y = 5i8;
    let marker_index = 0usize;
    let mut storage = WorldStorage::open(&rewritten_world, 0).expect("reopen for the marker");

    // Also rewrite `level.dat` through our model, so vanilla reads bytes we
    // produced on both sides of the world. The unknown entry is a probe: if
    // vanilla's datafixer keeps it, that is proof it read *our* document.
    let mut level = storage.level().cloned().expect("level.dat");
    level.time = 12_345;
    level.extra.push((
        "RustProbeMarker".to_owned(),
        mc_nbt::NbtTag::String("p03".to_owned()),
    ));
    storage.save_level(level).expect("writes our level.dat");

    let mut marked_chunk = storage
        .read_chunk(&Dimension::Overworld, marker_pos)
        .expect("reads the spawn chunk")
        .expect("spawn chunk present");
    let section = marked_chunk
        .section_index(marker_section_y)
        .expect("marker section exists");
    let previous = marked_chunk.sections[section]
        .block_states
        .get(marker_index)
        .cloned()
        .expect("index in range");
    marked_chunk.sections[section]
        .block_states
        .set(marker_index, marker.clone())
        .expect("sets the marker");
    storage
        .write_chunk_now(&Dimension::Overworld, marker_pos, &marked_chunk)
        .expect("writes the marked chunk");
    storage.close().expect("close after marking");
    println!(
        "marker {marker:?} written at section {marker_section_y} index {marker_index} \
         of {marker_pos:?} (was {previous:?})"
    );

    // --- 3: let vanilla load the rewritten world -----------------------------
    std::fs::copy(&jar, scratch.join("server.jar")).expect("copy server.jar");
    std::fs::write(scratch.join("eula.txt"), "eula=true\n").expect("eula");
    std::fs::write(
        scratch.join("server.properties"),
        format!(
            "level-name={world_name}\nonline-mode=false\nserver-port=25597\nmax-players=2\n\
             view-distance=6\nsimulation-distance=6\nlevel-seed=MC26RUSTPERSIST\n\
             sync-chunk-writes=true\n"
        ),
    )
    .expect("properties");

    let log = run_vanilla(&java, &scratch)
        .unwrap_or_else(|e| panic!("could not run the vanilla server: {e}"));
    println!("--- vanilla log tail ---\n{}", tail(&log, 40));
    println!("full log: {}", scratch.join("console.log").display());

    assert!(
        log.contains("Done ("),
        "vanilla never reached \"Done\" — the world did not load"
    );

    // Vanilla logs a WARN/ERROR line for every chunk it cannot parse, for a
    // level it cannot read, and for a chunk stored in the wrong location.
    for banned in [
        "Chunk file at",
        "is in the wrong location",
        "Failed to load",
        "Failed to parse",
        "Unable to read",
        "corrupt",
        "Corrupt",
        "Exception reading",
        "Invalid length for data",
        "Unknown chunk status",
        "level.dat",
    ] {
        let hits: Vec<&str> = log.lines().filter(|line| line.contains(banned)).collect();
        assert!(
            hits.is_empty(),
            "vanilla complained about {banned:?}:\n{}",
            hits.join("\n")
        );
    }

    // And the world must still be readable by us afterwards: vanilla re-saved it
    // on shutdown, so this also proves we read vanilla's post-26.1 output.
    let mut storage = WorldStorage::open(&rewritten_world, 0).expect("reopen after vanilla");
    let level = storage.level().cloned().expect("level.dat");
    assert_eq!(level.data_version, 4790);
    // Our level.dat was read by vanilla: the custom entry and the time we
    // stamped are still there (vanilla may bump `Time`, never reset it).
    assert!(
        level.time >= 12_345,
        "vanilla reset the world time to {}",
        level.time
    );
    println!(
        "level.dat probe after vanilla: RustProbeMarker={:?}",
        level
            .extra
            .iter()
            .find(|(key, _)| key == "RustProbeMarker")
            .map(|(_, value)| value.clone())
    );

    // The marker must have survived vanilla's own load + save cycle. If vanilla
    // had ignored our chunk and regenerated the terrain, this block would be
    // gone — so this assertion is what proves vanilla *read our bytes*.
    let marked_after = storage
        .read_chunk(&Dimension::Overworld, marker_pos)
        .expect("reads the spawn chunk after vanilla")
        .expect("spawn chunk still present");
    let section_after = marked_after
        .section_index(marker_section_y)
        .expect("marker section exists");
    let surviving_block = marked_after.sections[section_after]
        .block_states
        .get(marker_index)
        .cloned()
        .expect("index in range");
    assert_eq!(
        surviving_block, marker,
        "vanilla did not preserve the block we wrote into {marker_pos:?}; \
         it most likely regenerated the chunk instead of reading it"
    );
    println!("marker survived vanilla's load/save cycle: {surviving_block:?} at {marker_pos:?}");
    assert_eq!(level.data_version, 4790);
    let mut reread = 0usize;
    for (dimension, region_path) in &regions {
        let Some((region_x, region_z)) = region_coords(region_path) else {
            continue;
        };
        for local_x in 0..32 {
            for local_z in 0..32 {
                let pos = ChunkPos::new(region_x * 32 + local_x, region_z * 32 + local_z);
                match storage.read_chunk(dimension, pos) {
                    Ok(Some(_)) => reread += 1,
                    Ok(None) => {}
                    Err(e) => panic!("vanilla's re-save broke {pos:?} of {dimension}: {e}"),
                }
            }
        }
    }
    assert_eq!(
        reread, chunks_rewritten,
        "vanilla re-saved a different number of chunks than we wrote"
    );
    println!("vanilla re-saved {reread} chunks, all readable by us");
    let _ = std::fs::remove_dir_all(&scratch);
}

fn tail(text: &str, lines: usize) -> String {
    let all: Vec<&str> = text.lines().collect();
    all[all.len().saturating_sub(lines)..].join("\n")
}

/// Start vanilla on the rewritten world, wait for it to finish loading, ask it
/// to stop, and return its console log.
///
/// Output goes to files rather than pipes: a piped stdout nobody drains fills up
/// and deadlocks the server mid-save (a mistake this test made once, and the
/// reason the helper is explicit about it).
fn run_vanilla(java: &str, scratch: &Path) -> std::io::Result<String> {
    use std::io::Write;
    let log_path = scratch.join("console.log");
    let serve_log = scratch.join("stdout.log");
    let err_log = scratch.join("stderr.log");
    let mut child = Command::new(java)
        .arg("-Xmx2G")
        .arg("-jar")
        .arg("server.jar")
        .arg("nogui")
        .current_dir(scratch)
        .stdin(std::process::Stdio::piped())
        .stdout(std::fs::File::create(&serve_log)?)
        .stderr(std::fs::File::create(&err_log)?)
        .spawn()?;

    let combined = |a: &Path, b: &Path| {
        format!(
            "{}{}",
            std::fs::read_to_string(a).unwrap_or_default(),
            std::fs::read_to_string(b).unwrap_or_default()
        )
    };

    // Wait for world load (vanilla prints "Done (X.XXXs)!" once it is serving).
    let mut ready = false;
    for _ in 0..480 {
        std::thread::sleep(std::time::Duration::from_millis(500));
        if combined(&serve_log, &err_log).contains("Done (") {
            ready = true;
            break;
        }
        if child.try_wait()?.is_some() {
            break;
        }
    }
    if ready && let Some(stdin) = child.stdin.as_mut() {
        let _ = stdin.write_all(b"stop\n");
        let _ = stdin.flush();
    }
    drop(child.stdin.take());

    let mut exited = false;
    for _ in 0..240 {
        if child.try_wait()?.is_some() {
            exited = true;
            break;
        }
        std::thread::sleep(std::time::Duration::from_millis(500));
    }
    if !exited {
        let _ = child.kill();
        let _ = child.wait();
    }

    let log = combined(&serve_log, &err_log);
    std::fs::write(&log_path, &log)?;
    if !ready {
        return Err(std::io::Error::other(format!(
            "vanilla never reported \"Done\"; log:\n{}",
            tail(&log, 30)
        )));
    }
    Ok(log)
}

/// Reads the whole vanilla world without writing, and reports what it found.
///
/// This one has no java dependency, so it also runs on a machine that only has
/// the world directory: `cargo test -p mc-persistence --test
/// vanilla_differential -- --ignored`.
#[test]
#[ignore = "requires MC_VANILLA_WORLD"]
fn every_chunk_of_a_vanilla_world_decodes() {
    let source = env_path("MC_VANILLA_WORLD").expect("MC_VANILLA_WORLD must point at a world dir");
    let mut storage = WorldStorage::open(&source, 0).expect("open the vanilla world");
    let level = storage.level().cloned().expect("level.dat");
    assert!(
        LevelDat::is_supported_data_version(level.data_version),
        "unexpected DataVersion {}",
        level.data_version
    );

    let mut by_status: std::collections::BTreeMap<String, usize> =
        std::collections::BTreeMap::new();
    let mut total = 0usize;
    let mut with_light = 0usize;
    let mut with_entities = 0usize;
    for (dimension, path) in region_files(&source) {
        let Some((region_x, region_z)) = region_coords(&path) else {
            continue;
        };
        for local_x in 0..32 {
            for local_z in 0..32 {
                let pos = ChunkPos::new(region_x * 32 + local_x, region_z * 32 + local_z);
                let chunk = match storage.read_chunk(&dimension, pos) {
                    Ok(Some(chunk)) => chunk,
                    Ok(None) => continue,
                    Err(e) => panic!("cannot read {pos:?} of {dimension}: {e}"),
                };
                *by_status.entry(chunk.status.clone()).or_default() += 1;
                with_light += usize::from(chunk.light_correct);
                with_entities += usize::from(!chunk.entities.is_empty());
                total += 1;
            }
        }
    }
    println!("decoded {total} chunks ({with_light} lit, {with_entities} with entities)");
    for (status, count) in &by_status {
        println!("  {status}: {count}");
    }
    assert!(total > 0, "no chunks decoded");
}
