import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import net.minecraft.SharedConstants;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

/**
 * Dumps every block's <b>default block state</b> id, from the jar.
 *
 * <h2>Why this exists</h2>
 *
 * The registry's {@code default_state(name)} returned {@code first_state_id} — the <b>lowest</b> state id —
 * and that is not the same thing. Vanilla picks the default explicitly with
 * {@code registerDefaultState(...)}, and for a great many blocks it is not the first:
 *
 * <ul>
 *   <li>{@code oak_log} registers {@code axis} in the order {@code x, y, z} but defaults to <b>{@code y}</b>,
 *       so every log a world generator placed was lying on its side;</li>
 *   <li>{@code oak_leaves} registers {@code distance}, {@code persistent} and {@code waterlogged} and defaults
 *       to distance 7, persistent false, <b>waterlogged false</b>, so every leaf came out holding water.</li>
 * </ul>
 *
 * Both were reported by an owner looking at a tree, which is the only place the difference is visible: the
 * blocks are all real, the light is plausible, and nothing has an error.
 *
 * <h2>Method</h2>
 *
 * The same one {@code LightProbe} and {@code DumpRegistries} use: boot the server's own registry
 * ({@code SharedConstants.tryDetectVersion()} then {@code Bootstrap.bootStrap()}) and read
 * {@code Block.defaultBlockState()} from the same object graph the server uses. Nothing is transcribed and
 * nothing is inferred from ordering.
 *
 * <p><b>Line endings are written explicitly as LF.</b> {@code PrintWriter.println} uses the platform
 * separator, so on Windows the table came out CRLF while the repository holds LF, and the docs-audit
 * line-ending check failed on the working tree. The committed bytes were always right, which is exactly
 * why a generator that produces the wrong ones is worth fixing rather than normalising afterwards.
 *
 * <p>Output is one TSV of {@code <block name> <default state id>}, which the registry reads beside
 * {@code blocks.tsv}.
 *
 * <p>Local research tool (not part of the product crates).
 */
public final class DefaultStateProbe {
    public static void main(String[] args) throws Exception {
        Path out = Path.of(args.length > 0 ? args[0] : ".");
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();

        int blocks = 0;
        int differing = 0;
        try (PrintWriter writer = new PrintWriter(
                java.nio.file.Files.newBufferedWriter(
                        out.resolve("block_defaults.tsv"), StandardCharsets.UTF_8))) {
            writer.println("# Vanilla 26.1.2 default block state per block.");
            writer.println("# Generated by DefaultStateProbe.java from Block.defaultBlockState().");
            writer.println("# Format: <block name> <default state id>");
            writer.println("#");
            writer.println("# A block's default is chosen by registerDefaultState and is NOT in general its");
            writer.println("# lowest state id: oak_log registers axis as x,y,z and defaults to y, oak_leaves");
            writer.println("# registers distance/persistent/waterlogged and defaults to 7/false/false.");
            for (Block block : BuiltInRegistries.BLOCK) {
                BlockState state = block.defaultBlockState();
                int id = Block.BLOCK_STATE_REGISTRY.getId(state);
                String name = BuiltInRegistries.BLOCK.getKey(block).toString();
                int first = Block.BLOCK_STATE_REGISTRY.getId(block.getStateDefinition().any());
                blocks++;
                if (id != first) {
                    differing++;
                }
                writer.print(name + " " + id + "\\n");
            }
        }
        System.out.println("blocks=" + blocks + " default_differs_from_lowest=" + differing);
    }
}
