import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import net.minecraft.SharedConstants;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;

/**
 * Dumps the three inputs a light engine needs, from the jar that the client is built against.
 *
 * Method: the same one {@code DumpRegistries} uses — boot the server's own registry
 * ({@code SharedConstants.tryDetectVersion()} then {@code Bootstrap.bootStrap()}, exactly the pair the
 * dedicated server runs) and read the accessors the jar's own light engine reads:
 *
 * <ul>
 *   <li>{@code getLightEmission()} — the block-light value this state emits, 0..15</li>
 *   <li>{@code getLightDampening()} — how much light is absorbed passing through it</li>
 *   <li>{@code propagatesSkylightDown()} — whether sky light passes straight down undiminished</li>
 * </ul>
 *
 * Nothing is guessed and no table is transcribed: these are the values {@code LevelLightEngine} uses, read
 * from the same object graph the server uses. That matters here more than usual, because a wrong dampening
 * produces light that is plausible everywhere and correct nowhere.
 *
 * <p>Output is one TSV. Most blocks have one triple across all their states, so those get a single
 * {@code block} row; a block whose states differ (a lit furnace, a redstone lamp, a light block) gets a
 * {@code state} row per state id instead. Lossless and far smaller than 29 873 rows of mostly repeats.
 *
 * <p><b>A block row carries its state range</b> — {@code block <name> <first state id> <count> <emission>
 * <dampening> <propagates>}. An earlier version wrote only the name, and the parser downstream collected those
 * rows into a list it never read, so every common terrain block kept the default "transparent air". The
 * differential test against a real server is what caught it; nothing else could, because the file looked
 * right, the parser ran, and the engine's output was well-formed.
 *
 * <p>Local research tool (not part of the product crates).
 */
public final class LightProbe {
    public static void main(String[] args) throws Exception {
        Path out = Path.of(args.length > 0 ? args[0] : ".");
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();

        Files.createDirectories(out);
        try (PrintWriter w = new PrintWriter(Files.newBufferedWriter(
                out.resolve("block_light.tsv"), StandardCharsets.UTF_8))) {
            w.println("# Vanilla 26.1.2 per-block light properties, from BlockStateBase.");
            w.println("# Generated by LightProbe.java; the same registry the dedicated server boots.");
            w.println("# Format: block <name> <first state id> <state count> <emission> <dampening>"
                    + " <propagates_skylight_down:0|1>");
            w.println("#         state <state id> <emission> <dampening> <propagates_skylight_down:0|1>");
            w.println("# A block gets one 'block' row when every state shares a triple, and one 'state' row per");
            w.println("# state otherwise. The range is on the row so a parser can apply it without the block");
            w.println("# registry; without it a row cannot be applied at all. Emission is 0..15, dampening 0..15.");

            int blockRows = 0;
            int stateRows = 0;
            for (Block block : BuiltInRegistries.BLOCK) {
                List<BlockState> states = block.getStateDefinition().getPossibleStates();
                Map<String, Integer> triples = new LinkedHashMap<>();
                boolean uniform = true;
                String first = null;
                for (BlockState state : states) {
                    String triple = triple(state);
                    if (first == null) {
                        first = triple;
                    } else if (!first.equals(triple)) {
                        uniform = false;
                    }
                    triples.merge(triple, 1, Integer::sum);
                }
                String name = BuiltInRegistries.BLOCK.getKey(block).toString();
                if (uniform) {
                    int firstState = states.isEmpty() ? -1 : Block.getId(states.get(0));
                    w.println("block\t" + name + "\t" + firstState + "\t" + states.size() + "\t" + first);
                    blockRows++;
                } else {
                    for (BlockState state : states) {
                        w.println("state\t" + Block.getId(state) + "\t" + triple(state));
                        stateRows++;
                    }
                }
            }
            w.flush();
            System.out.println("block rows: " + blockRows);
            System.out.println("state rows: " + stateRows);
        }
    }

    private static String triple(BlockState state) {
        return state.getLightEmission() + "\t" + state.getLightDampening() + "\t"
                + (state.propagatesSkylightDown() ? "1" : "0");
    }
}
