#!/usr/bin/env python3
"""Evidence tool: extract committed P03 fixtures from the vanilla world.

Produces, under target/vanilla-26.1.2/fixtures-out/:
  level_26_1_2.dat        verbatim vanilla level.dat (gzip)
  chunk_26_1_2.nbt        decompressed NBT of one real vanilla chunk
  region_26_1_2.mca       derived region file: vanilla 8 KiB header (one slot
                          rewritten to sector 2) + that chunk's verbatim sectors
  MANIFEST.txt            sha256 + provenance for each file

Local throwaway research helper (not part of the product crates).
"""

import gzip
import hashlib
import os
import struct
import sys
import zlib

sys.path.insert(0, __file__.rsplit("\\", 1)[0])
from nbt_dump import Reader, read_payload

SECTOR = 4096


def load_chunk(data, slot):
    o = struct.unpack(">1024I", data[0:SECTOR])[slot]
    if o == 0:
        return None
    start = (o >> 8) * SECTOR
    length = struct.unpack(">I", data[start : start + 4])[0]
    comp = data[start + 4]
    payload = data[start + 5 : start + 4 + length]
    raw = {1: gzip.decompress, 2: zlib.decompress, 3: lambda b: b}[comp](payload)
    r = Reader(raw)
    tag = r.u8()
    r.u16()
    return o, comp, raw, read_payload(r, tag)


def palette_sizes(tree):
    sizes = []
    for s in tree.get("sections", []):
        bs = s.get("block_states", {})
        bi = s.get("biomes", {})
        sizes.append((len(bs.get("palette", [])), len(bi.get("palette", []))))
    return sizes


def main():
    base = os.path.dirname(os.path.abspath(__file__))
    world = os.path.join(base, "vanilla-world-26.1.2", "world")
    level = os.path.join(world, "level.dat")
    region = os.path.join(
        world, "dimensions", "minecraft", "overworld", "region", "r.-2.-1.mca"
    )
    out = os.path.join(base, "fixtures-out")
    os.makedirs(out, exist_ok=True)

    data = open(region, "rb").read()
    offsets = struct.unpack(">1024I", data[0:SECTOR])

    best = None
    for slot in range(1024):
        if offsets[slot] == 0:
            continue
        got = load_chunk(data, slot)
        if got is None:
            continue
        o, comp, raw, tree = got
        sizes = palette_sizes(tree)
        max_block_palette = max((b for b, _ in sizes), default=0)
        has_lights = any("SkyLight" in s or "BlockLight" in s for s in tree.get("sections", []))
        score = (
            max_block_palette > 8,          # exercises >4-bit packing
            bool(tree.get("Heightmaps")),   # exercises heightmaps
            has_lights,                     # exercises light arrays
            tree.get("Status") == "minecraft:full",
            len(tree.get("entities", [])),
            -len(raw),                      # prefer the smallest
        )
        if best is None or score > best[0]:
            best = (score, slot, o, comp, raw, tree, sizes, has_lights)

    score, slot, o, comp, raw, tree, sizes, has_lights = best
    print(f"chosen slot={slot} sectors={o & 0xFF} comp={comp} decompressed={len(raw)}")
    print(f"  xPos={tree.get('xPos')} zPos={tree.get('zPos')} status={tree.get('Status')}")
    print(f"  block palettes: {[b for b, _ in sizes]}")
    print(f"  biome palettes: {[b for _, b in sizes]}")
    print(f"  heightmaps={sorted(tree.get('Heightmaps', {}).keys())} lights={has_lights}")

    # --- fixtures ---
    level_bytes = open(level, "rb").read()
    with open(os.path.join(out, "level_26_1_2.dat"), "wb") as fh:
        fh.write(level_bytes)

    recompressed = zlib.compress(raw, 6)
    body = struct.pack(">I", len(recompressed) + 1) + bytes([2]) + recompressed
    print(f"  recompressed with zlib: {len(recompressed)} bytes (vanilla on-disk payload was {len(data) and struct.unpack('>I', data[(o >> 8) * SECTOR:(o >> 8) * SECTOR + 4])[0] - 1} bytes)")
    sectors = (len(body) + SECTOR - 1) // SECTOR
    padded = body + b"\x00" * (sectors * SECTOR - len(body))

    header = bytearray(2 * SECTOR)
    struct.pack_into(">I", header, slot * 4, (2 << 8) | sectors)
    struct.pack_into(">i", header, SECTOR + slot * 4, 0)
    region_fixture = bytes(header) + padded
    with open(os.path.join(out, "region_26_1_2.mca"), "wb") as fh:
        fh.write(region_fixture)

    lines = [
        "# Provenance: generated by vanilla Minecraft Java 26.1.2 (server.jar sha1",
        "# 97ccd4c0ed3f81bbb7bfacddd1090b0c56f9bc51), seed 1361882806, default world",
        "# preset, then saved by the vanilla shutdown path. See docs/research/provenance.md.",
        "",
    ]
    for name in ("level_26_1_2.dat", "region_26_1_2.mca"):
        blob = open(os.path.join(out, name), "rb").read()
        lines.append(f"{name}  {len(blob)} bytes  sha256={hashlib.sha256(blob).hexdigest()}")
    lines.append("")
    lines.append(
        f"chunk slot {slot} = chunk (x={tree.get('xPos')}, z={tree.get('zPos')}), "
        f"status {tree.get('Status')}, DataVersion {tree.get('DataVersion')}"
    )
    lines.append(f"chunk decompressed nbt = {len(raw)} bytes sha256={hashlib.sha256(raw).hexdigest()}")
    lines.append(f"region fixture layout: header (2 sectors) + chunk at sector 2, {sectors} sector(s)")
    text = "\n".join(lines) + "\n"
    with open(os.path.join(out, "MANIFEST.txt"), "w", encoding="utf-8") as fh:
        fh.write(text)
    print(text)


if __name__ == "__main__":
    main()
