[package]
name = "mc-world"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
mc-core = { path = "../core" }
mc-nbt = { path = "../nbt" }
mc-persistence = { path = "../persistence" }
mc-registry = { path = "../registry" }
tracing.workspace = true

[dev-dependencies]
mc-test-support = { path = "../test-support" }
