[package]
name = "mc-persistence"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mc-core = { path = "../core" }
mc-nbt = { path = "../nbt" }
flate2.workspace = true
tracing.workspace = true

[dev-dependencies]
mc-test-support = { path = "../test-support" }
