[package]
name = "mc-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
mc-core = { path = "../core" }
mc-protocol = { path = "../protocol" }
md-5.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "net", "io-util", "sync", "time", "macros"] }
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
mc-test-support = { path = "../test-support" }
